[package]
name = "maturity-macro"
description = "Procedural macros for code maturity annotations."
keywords = ["maturity", "stability", "metrics", "attribute", "annotation"]
categories = ["development-tools"]
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true

[lib]
proc-macro = true

[dependencies]
