[package]
name = "cargo-maturity"
description = "Cargo subcommand for generating maturity reports."
keywords = ["maturity", "stability", "metrics", "cargo-plugin"]
categories = ["development-tools", "development-tools::cargo-plugins"]
version = "0.1.3"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
maturity-report.workspace = true
