[package]
name = "cargo-maturity"
description = "Cargo subcommand for generating maturity reports."
keywords = ["maturity", "stability", "metrics", "cargo-plugin"]
categories = ["development-tools", "development-tools::cargo-plugins"]
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
maturity-report.workspace = true
